language: node_js
node_js:
  - "5"
before_install:
  - sudo apt-get install -y calibre
  - sudo apt-get install xvfb
install:
  - npm install gitbook-plugin-chapter-fold
  - npm install gitbook-plugin-image-captions
  - npm install gitbook-plugin-fancybox
  - npm install gitbook-plugin-pageload-analytics
before_script:
  - npm install gitbook-cli
  - npm install gitbook-publish@latest
  - npm install ebook-convert
  - sudo mv /usr/bin/ebook-convert /usr/bin/ebook-convert2
  - sudo cp ./ebook-wrapper.sh /usr/bin/ebook-convert
  - sudo chmod +x /usr/bin/ebook-convert
script: 
  - git config --global user.email "patrick@janssen.name"
  - git config --global user.name "Patrick"
  - gitpub
  - git branch
  - git remote -v
  - git push --force "https://{USER_NAME}:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}" gh-pages 
